### ISSUE TITLE
Exception with news 9.2.0 and md_newsfrontend 3.0.0

### ISSUE THREAD

**Issue by bzgaLindner** [cdaecke/md_newsfrontend#23] opened 2022-02-08 08:38 UTC
Hi,.
with a fresh installation of news 9.2.0 and md_newsfrontend 3.0.0 on TYPO3 10.4.23 I get 

> PHP Warning: Declaration of Mediadreams\MdNewsfrontend\Domain\Model\News::setTxMdNewsfrontendFeuser(TYPO3\CMS\Extbase\Domain\Model\FrontendUser $txMdNewsfrontendFeuser) should be compatible with GeorgRinger\News\Domain\Model\News::setTxMdNewsfrontendFeuser(GeorgRinger\News\Domain\Model\FrontendUser $txMdNewsfrontendFeuser) in /home/www/foo/pub/typo3conf/ext/md_newsfrontend/Classes/Domain/Model/News.php line 121

directly after installing md_newsfrontend from TER (also when emptying the cache files).

Best,
Dominik

**Comment by cdaecke** [comment] 2022-02-08 11:23
Thanks for reporting!

I have pushed a fix. Could you please double check, if this works for you?

**Comment by bzgaLindner** [comment] 2022-02-08 11:38
Hey,
works for $txMdNewsfrontendFeuser, but now I get:

> PHP Warning: Declaration of Mediadreams\MdNewsfrontend\Domain\Model\News::removeFalMedia(TYPO3\CMS\Extbase\Domain\Model\FileReference $imageToRemove) should be compatible with GeorgRinger\News\Domain\Model\News::removeFalMedia(GeorgRinger\News\Domain\Model\FileReference $imageToRemove) in /home/www/webadmin/sites/testumgebung1.bzga.de/pub/typo3conf/ext/md_newsfrontend/Classes/Domain/Model/News.php line 0
I guess it the same problem?

**Comment by cdaecke** [comment] 2022-02-08 19:26
I could not reproduce this error, but changed the import of `FileReference` in the News models as well.

Is it working for you with the second change?

**Comment by bzgaLindner** [comment] 2022-02-09 07:53
Hey,
works with https://github.com/cdaecke/md_newsfrontend/commit/d4216a6c0e6ba679dd25a19371d40099d094e8c0

Thank you!

**Closed as completed** 2022-02-09 07:54 UTC
Labels: bug

**Comment by cdaecke** [comment] 2022-02-09 08:36
Version 3.0.1 is released.
