### ISSUE TITLE
Delete all categories on a news item

### ISSUE THREAD

**Issue by sneopu** [cdaecke/md_newsfrontend#18] opened 2019-12-10 11:30 UTC
At this time it is not possible to remove all assigned categories on a news item.

A empty categories array in the post request will be removed by the following lines:
https://github.com/cdaecke/md_newsfrontend/blob/914c02461318eae822eb9db8cd1a76f4685f97fe/Classes/Controller/BaseController.php#L163-L167

Is this behavior intentional? 
On my test with TYPO3 v9.5.11 I see no drawback after removing the lines.
If you want I can provide a pull request.

**Comment by cdaecke** [comment] 2019-12-13 12:17
Thanks for reporting!
This is definitely not the intended behaviour and was fixed with the attached commit (like you have proposed).

Are you able to double check, if this is working for you?

**Comment by cdaecke** [comment] 2020-01-08 17:20
A new version of the extension is published.

**Closed as completed by cdaecke** 2020-01-08 17:20 UTC
Labels: bug
